version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
    networks:
      - app_net

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24